config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  get 'terms', to: 'pages#terms'
  get 'policy', to: 'pages#policy'
  get 'questions', to: 'questions#index'
  resources 'profiles' do
    resources 'experiences'
    resources 'introductions'
    resources 'interviews'
    resources 'questions' do
      resources 'answers'
    end
  end
  get 'admin', to: 'admin#index'
  namespace 'admin' do
    resources 'profiles'
    resources 'experiences'
    resources 'questions'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :profile
  belongs_to :question
end

app/models/batch.rb
class Batch < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :batch
  belongs_to :country

  def full_name
    batch.name + name
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :profile

  validates :title, presence: true, length: { maximum: 255 }
  validates :place, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/interview.rb
class Interview < ApplicationRecord
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :introducer, class_name: 'Profile', foreign_key: 'introducer_id'
  belongs_to :introduced, class_name: 'Profile', foreign_key: 'introduced_id'
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/major.rb
class Major < ApplicationRecord
  def full_name
    faculty_name + department_name
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :major
  belongs_to :job
  has_many :profile_course, dependent: :destroy
  has_many :experience, dependent: :destroy
  has_many :introducer_introduction, class_name: 'Introduction', foreign_key: 'introducer_id'
  has_many :introduced_introduction, class_name: 'Introduction', foreign_key: 'introduced_id'
  has_many :questioner_question, class_name: 'Question', foreign_key: 'questioner_id'
  has_many :questioned_question, class_name: 'Question', foreign_key: 'questioned_id'
  has_many :response, dependent: :destroy
  has_many :interview, class_name: 'Interview', foreign_key: 'interview_id'
  accepts_nested_attributes_for :profile_course, allow_destroy: true
  validates :user_id, uniqueness: true
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :nickname, presence: true, length: { maximum: 255 }
  validates :birthday, presence: true
  validates :major_id, presence: true
  validates :avatar_image, presence: true
  validates :facebook, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :instagram, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :twitter, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :url_title, length: { maximum: 7 }
  validates :url, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :description, length: { maximum: 255 }
  enum sex: { 女性: 0, 男性: 1, その他: 2 }
  enum usertype: { 学生: 0, スタッフ: 1 }
  enum graduated: { 在学: 0, 既卒: 1 }
  has_attached_file :avatar_image, PAPERCLIP_STORAGE_OPTS
  validates_attachment_content_type :avatar_image, content_type: %r{\Aimage\/.*\Z}

  def full_name
    last_name + first_name
  end
end

app/models/profile_course.rb
class ProfileCourse < ApplicationRecord
  belongs_to :profile
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questioner, class_name: 'Profile', foreign_key: 'questioner_id'
  belongs_to :questioned, class_name: 'Profile', foreign_key: 'questioned_id'
  has_many :answer, dependent: :destroy
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :interview
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable,
         invite_for: 24.hours
  has_one :profile, dependent: :destroy
  has_one :role, dependent: :destroy

  attr_accessor :mode

  def admin?
    role.present?
  end

  def save_role(new_role)
    if role
      role.update(admin_role: new_role)
    else
      role.create_role(admin_role: new_role)
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  def index
    @questions = Question.all
  end

  def show
    @answers = Answer.where(question_id: @question.id)
  end

  def new
    redirect_to root_path if @profile&.id == current_user.id
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.questioned_id = @profile.id
    @question.questioner_id = current_user.profile.id if current_user
    if @question.save
      redirect_to profile_question_url(@profile, @question), notice: '質問を作成しました'
    else
      render :new
    end
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    if @question.update(question_params)
      redirect_to profile_url(@question.questioned_id), notice: '質問を更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to profile_url(@question.questioned_id), notice: '質問を削除しました'
    else
      redirect_to profile_url(@question.questioned_id), notice: '質問を削除に失敗しました'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :login_required
  before_action :set_question, only: %i[new show edit update destroy]
  before_action :set_profile, only: %i[new show create edit update]
  before_action :raise_unless_own_question, only: %i[edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    # @questioned_question = Question.find_by(questioned_id: params[:profile_id])
    @answers = Answer.where(question_id: @question.id)
  end

  def new
    redirect_to root_path if @profile&.id == current_user.id
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.questioned_id = @profile.id
    @question.questioner_id = current_user.profile.id if current_user
    if @question.save
      redirect_to profile_question_url(@profile, @question), notice: '質問を作成しました'
    else
      render :new
    end
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    if @question.update(question_params)
      redirect_to profile_url(@question.questioned_id), notice: '質問を更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to profile_url(@question.questioned_id), notice: '質問を削除しました'
    else
      redirect_to profile_url(@question.questioned_id), notice: '質問を削除に失敗しました'
    end
  end

  private

  def login_required
    redirect_to root_path unless current_user
  end

  def raise_unless_own_question
    redirect_to root_path unless current_user.present? && @question&.questioner_id == current_user.id
  end

  def set_profile
    @profile = Profile.find_by(id: params[:profile_id])
  end

  def set_question
    @question = Question.find_by(id: params[:id])
  end

  def question_params
    params.require(:question).permit(
      %i[questioner_id questioned_id title description created_at updated_at]
    )
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      space_after_headers: true,
      with_toc_data: true
    }

    extensions = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="container">
  <%= form_for [:profile, @question] do |f| %>
    <div class="row">
      <div class="col-12">
        <%= f.label :title, "題名" %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= raw errmessage(@question, "title") %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= f.label :description, "質問文" %>
        <%= f.text_area :description, size: '30x15', class:'form-control' %>
        <%= raw errmessage(@question, "description") %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <button type="submit" class="mt-4 btn btn-lg btn-block btn-primary">登録する</button>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<article class="col-12 resume-wrapper text-center position-relative">
  <%= link_to(profile_question_url(question.questioner, question),style: 'text-decoration:none;') do %>
  <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
    <div class="resume-header pt-4 pt-md-0">
      <div class="media flex-column flex-md-row">
        <%= image_tag(question.questioner.avatar_image.url(:medium), class: 'mr-3 img-fluid picture mx-auto') %>
        <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
          <div class="primary-info">
            <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
              <%= question.title %>
            </h2>
            <p><%= question.description %><p>
              <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
                From <%= question.questioner.nickname %>
                <br class="d-block d-sm-none">
                To <%= question.questioned.nickname %>
              </h2>
            </div>
          </div>
          <%= image_tag(question.questioned.avatar_image.url(:medium), class: 'mb-4 mr-3 img-fluid picture mx-auto') %>
        </div>
      </div>
    </div>
    <% end %>
  </article>

app/views/questions/edit.html.erb
<div class="top_main-content mt-4">
  <h3 class="text-center">質問文編集</h3>
  <%= render partial: "form" %>
</div>

app/views/questions/index.html.erb
<h3 class="mt-4 text-center">質問一覧</h3>
<div class="mt-4">
  <div class="container">
    <div class="row mb-2">
      <%= render @questions %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="top_main-content mt-4">
  <h3 class="text-center">質問文追加</h3>
  <%= render partial: "form" %>
</div>

app/views/questions/show.html.erb
<article class="resume-wrapper text-center position-relative">
  <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
    <div class="resume-header pt-4 pt-md-0">
      <div class="media flex-column flex-md-row">
        <%= link_to(profile_url(@question.questioner), class: 'mx-auto') do %>
        <%= image_tag(@question.questioner.avatar_image.url(:medium), class: 'mr-3 img-fluid picture mx-auto') %>
        <% end %>
        <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
          <div class="primary-info">
            <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
              <%= @question.title %>
            </h2>
            <p><%= @question.description %><p>
              <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
                <%= link_to @question.questioned.nickname, profile_url(@question.questioned) %>へ
                <%= link_to @question.questioner.nickname, profile_url(@question.questioner) %>より
                <br class="d-block d-sm-none">
                <% if @question.questioner.user_id == current_user.id %>
                <%= link_to '編集', edit_profile_question_url(@profile, @question), class: 'btn btn-sm btn-outline-secondary' %>
                <%= link_to '削除', profile_question_url(@profile, @question), method: :delete, class: 'btn btn-sm btn-outline-secondary' %>
                <% end %>
                <%= link_to '返信', new_profile_question_answer_url(@profile, @question), class: 'btn btn-sm btn-outline-secondary' %>
              </h2>
            </div>
          </div>
          <%= link_to(profile_url(@question.questioned), class: 'mx-auto') do %>
          <%= image_tag(@question.questioned.avatar_image.url(:medium), class: 'mb-4 mr-3 img-fluid picture mx-auto') %>
          <% end %>
        </div>
      </div>
    </div>
  </article>
  <% @answers.all.each do |answer| %>
  <article class="resume-wrapper text-center position-relative">
    <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
      <div class="resume-header pt-4 pt-md-0">
        <div class="media flex-column flex-md-row">
          <%= link_to(profile_url(answer.profile), class: 'mx-auto') do %>
          <%= image_tag(answer.profile.avatar_image.url(:medium), class: 'mr-3 img-fluid picture mx-auto') %>
          <% end %>
          <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
            <div class="primary-info">
              <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
                <%= link_to answer.profile.nickname, profile_url(answer.profile) %>
                <br class="d-block d-sm-none">
              </h2>
              <p><%= answer.description %><p>
              </div>
              <% if answer.profile_id == current_user.id %>
              <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">
                <%= link_to '編集', edit_profile_question_answer_url(@profile, @question, answer), class: 'btn btn-sm btn-outline-secondary' %>
                <%= link_to '削除', profile_question_answer_url(@profile, @question, answer), method: :delete, class: 'btn btn-sm btn-outline-secondary' %>
              </h2>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </article>
    <% end %>