config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  get 'terms', to: 'pages#terms'
  get 'policy', to: 'pages#policy'
  get 'questions', to: 'questions#index'
  resources 'profiles' do
    resources 'experiences'
    resources 'introductions'
    resources 'interviews'
    resources 'questions' do
      resources 'answers'
    end
  end
  get 'admin', to: 'admin#index'
  namespace 'admin' do
    resources 'profiles'
    resources 'experiences'
    resources 'questions'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :profile
  belongs_to :question
end

app/models/batch.rb
class Batch < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :batch
  belongs_to :country

  def full_name
    batch.name + name
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :profile

  validates :title, presence: true, length: { maximum: 255 }
  validates :place, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/interview.rb
class Interview < ApplicationRecord
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :introducer, class_name: 'Profile', foreign_key: 'introducer_id'
  belongs_to :introduced, class_name: 'Profile', foreign_key: 'introduced_id'
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/major.rb
class Major < ApplicationRecord
  def full_name
    faculty_name + department_name
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :major
  belongs_to :job
  has_many :profile_course, dependent: :destroy
  has_many :experience, dependent: :destroy
  has_many :introducer_introduction, class_name: 'Introduction', foreign_key: 'introducer_id'
  has_many :introduced_introduction, class_name: 'Introduction', foreign_key: 'introduced_id'
  has_many :questioner_question, class_name: 'Question', foreign_key: 'questioner_id'
  has_many :questioned_question, class_name: 'Question', foreign_key: 'questioned_id'
  has_many :response, dependent: :destroy
  has_many :interview, class_name: 'Interview', foreign_key: 'interview_id'
  accepts_nested_attributes_for :profile_course, allow_destroy: true
  validates :user_id, uniqueness: true
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :nickname, presence: true, length: { maximum: 255 }
  validates :birthday, presence: true
  validates :major_id, presence: true
  validates :avatar_image, presence: true
  validates :facebook, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :instagram, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :twitter, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :url_title, length: { maximum: 7 }
  validates :url, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :description, length: { maximum: 255 }
  enum sex: { 女性: 0, 男性: 1, その他: 2 }
  enum usertype: { 学生: 0, スタッフ: 1 }
  enum graduated: { 在学: 0, 既卒: 1 }
  has_attached_file :avatar_image, PAPERCLIP_STORAGE_OPTS
  validates_attachment_content_type :avatar_image, content_type: %r{\Aimage\/.*\Z}

  def full_name
    last_name + first_name
  end
end

app/models/profile_course.rb
class ProfileCourse < ApplicationRecord
  belongs_to :profile
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questioner, class_name: 'Profile', foreign_key: 'questioner_id'
  belongs_to :questioned, class_name: 'Profile', foreign_key: 'questioned_id'
  has_many :answer, dependent: :destroy
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :interview
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable,
         invite_for: 24.hours
  has_one :profile, dependent: :destroy
  has_one :role, dependent: :destroy

  attr_accessor :mode

  def admin?
    role.present?
  end

  def save_role(new_role)
    if role
      role.update(admin_role: new_role)
    else
      role.create_role(admin_role: new_role)
    end
  end
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminController
  def index
    @profiles = Profile.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :login_required
  before_action :set_profile, only: %i[show new create edit update]

  def index
    @q = Profile.ransack(params[:q])
    @profiles = @q.result(distinct: true).sort_by { rand }
  end

  # rubocop:disable Metrics/AbcSize
  def show
    @profile = Profile.find_by(user_id: params[:id])
    @experiences = Experience.where(profile_id: params[:id]).order('period_from DESC').paginate(page: params[:page], per_page: 4)
    @introduced_introductions = Introduction.where(introduced_id: params[:id])
    @introducer_introductions = Introduction.where(introducer_id: params[:id])
    @questioner_questions = Question.where(questioner_id: params[:id])
    @questioned_questions = Question.where(questioned_id: params[:id])
    @response = Response.find_by(interview_id: 1, profile_id: params[:id])
  end
  # rubocop:enable Metrics/AbcSize

  def new
    @profile = Profile.new
    @profile.profile_course.build
  end

  def create
    @profile = Profile.new(profile_params)
    if current_user
      @profile.id = current_user.id
      @profile.user_id = current_user.id
    end
    if @profile.save
      redirect_to profile_url(@profile.user_id), notice: 'プロフィールを作成しました'
      notify_create_profile(@profile)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @profile.update(update_team_params)
      redirect_to profile_url(@profile.user_id), notice: 'プロフィールを更新しました'
    else
      render :edit
    end
  end

  def destroy; end

  private

  def login_required
    redirect_to root_path unless current_user
  end

  def set_profile
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def notify_create_profile(profile)
    User.all.find_each do |user|
      next if user.email.blank? || (user == profile.user)

      ProfileMailer.notify_create_profile(profile, user.email).deliver if Rails.env.production?
    end
  end

  def profile_params
    params.require(:profile).permit(
      permit_params,
      profile_course_attributes: [:course_id]
    )
  end

  def update_team_params
    params.require(:profile).permit(
      permit_params,
      profile_course_attributes: %i[course_id _destroy id]
    )
  end

  def permit_params
    %i[user_id usertype first_name last_name nickname sex birthday school major_id graduated job_id description avatar_image facebook instagram twitter url_title url]
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      space_after_headers: true,
      with_toc_data: true
    }

    extensions = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/profiles/index.html.erb
<div class="mx-auto" style="width: 95%">
  <table class="mx-auto">
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>性別</th>
      <th>誕生日</th>
      <th>大学</th>
      <th>学部</th>
      <th>卒</th>
      <th>仕事</th>
      <th>自己紹介</th>
      <th>経験数</th>
      <th>最終ログイン</th>
      <th>ログイン回数</th>
      <th>SNS</th>
    </tr>
    <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.id %></td>
      <td><%= link_to profile.full_name, profile_url(profile.id) %></td>
      <td><%= profile.sex %></td>
      <td><%= profile.birthday %></td>
      <td><%= profile.school %></td>
      <td><%= profile.major.full_name %></td>
      <td><%= profile.graduated %></td>
      <td><%= profile.job.name %></td>
      <td><%= truncate(profile.description, length:40	) %></td>
      <td><%= profile.experience.count %></td>
      <td><%= profile.user.current_sign_in_at %></td>
      <td><%= profile.user.sign_in_count %></td>
      <td>
        <p>
          <%= link_to_if profile.facebook.present?, 'F', profile.facebook, target:'_blank' %>
          <%= link_to_if profile.twitter.present?, 'T', profile.twitter, target:'_blank' %>
          <%= link_to_if profile.instagram.present?, 'I', profile.instagram, target:'_blank' %>
        </p>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/profiles/_form.html.erb
<div class="container">
  <%= form_for(@profile) do |f| %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :last_name, "苗字" %>
      <%= f.text_field :last_name, class: 'form-control' %>
      <%= raw errmessage(@profile, "last_name") %>

    </div>
    <div class="form-group col-md-6">
      <%= f.label :first_name, "名前" %>
      <%= f.text_field :first_name, class: 'form-control' %>
      <%= raw errmessage(@profile, "first_name") %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :nickname , "ニックネーム"%>
      <%= f.text_field :nickname, class: 'form-control' %>
      <%= raw errmessage(@profile, "nickname") %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :avatar_image , "プロフィール画像"%>
      <%= f.file_field :avatar_image, class: 'form-control' %>
      <%= raw errmessage(@profile, "avatar_image") %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :sex, "性別" %>
      <%= f.select :sex, Profile.sexes.keys.to_a, {}, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :birthday, "生年月日" %>
      <div class= "form-control">
        <%= raw sprintf(
          f.date_select( 
            :birthday, 
            :use_month_numbers  => true , 
            :start_year => 1950,
            :end_year => -18.year.from_now.year, 
            :default => Date.new(2000, 1, 1), 
            :date_separator => '%s'
          ), '年', '月') + '日'
        %> 
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :usertype, "Diversity Voyage - 参加タイプ" %>
      <%= f.select :usertype, Profile.usertypes.keys.to_a, {}, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.fields_for :profile_course do |course_field| %>
      <%= course_field.label :course_id, "Diversity Voyage - 参加コース" %>
      <%= course_field.select :course_id, Course.all.map{|i| [i.full_name, i.id]}, {:prompt => '選択してください'}, class: 'form-control'  %>
      <% end %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :school, "学校名" %>
      <%= f.text_field :school, class: 'form-control', value: '東洋大学' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :major_id, "専攻(東洋生用)" %>
      <%= f.select :major_id, Major.all.map{|i| [i.full_name, i.id]}, {:prompt => '選択してください'}, class:'form-control'%>
      <%= raw errmessage(@profile, "major_id") %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :graduated, "在学/既卒" %>
      <%= f.select :graduated, Profile.graduateds.keys.to_a, {}, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :job_id, "職業" %>
      <%= f.select :job_id, Job.all.map{|i| [i.name, i.id]}, {:prompt => '選択してください'}, class:'form-control' %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :facebook, "Facebook URL" %>
      <%= f.text_field :facebook, class: 'form-control', placeholder: 'facebook_url' %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :instagram, "Instagram URL" %>
      <%= f.text_field :instagram, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :twitter, "Twitter URL" %>
      <%= f.text_field :twitter, class: 'form-control' %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :url_title, "その他のURLのタイトル" %>
      <%= f.text_field :url_title, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :url, "その他のURL" %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "自己紹介" %>
    <%= f.text_area :description, size: '30x15', class:'form-control' %>
  </div>
  <button type="submit" class="btn btn-primary">登録する</button>
  <% end %>
</div>

app/views/profiles/_profile.html.erb
<div class="col-md-6">
  <%= link_to(profile_url(profile), class: "text-dark gtm-profiles-#{profile.id}", style:'text-decoration: none;') do %>
  <div class="profile-card card flex-md-row mb-4 shadow-sm h-md-250">
    <%= image_tag(profile.avatar_image.url(:medium), class: 'profile-card-image card-img-right flex-auto') if profile.avatar_image.present? %>
    <div class="card-body d-flex flex-column align-items-start">
      <h3 class="mb-2">
        <%= profile.full_name %>
      </h3>
      <% if profile.major.full_name.present? %>
        <p class="mb-auto">学部: <%= profile.major.full_name %></p>
      <% end %>
      <% profile.profile_course.each do |profile_course| %>
        <p class="mb-auto">コース: <%= profile_course.course.full_name %></p>
      <% end %>
      <p class="mb-auto">職業: <%= profile.job.name %></p>
      <p class="card-text mb-auto"><%= truncate(strip_tags(markdown(profile.description))) %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/profiles/_search.html.erb
<div class="row mb-4">
  <div class="col-md-12 p-4 search-container">

  <div class="container-fluid">
    <%= search_form_for @q do |f| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :first_name_or_last_name_cont, "氏名" %>
        <%= f.search_field :first_name_or_last_name_cont, class: 'form-control form-control-sm' %>
      </div>
      <div class="form-group col-md-1">
        <%= f.label :sex, "性別" %>
        <%= f.select :sex_eq, Profile.sexes.to_a.map { |w| [w[0].humanize, w[1]] }, {:include_blank => true}, class: 'form-control form-control-sm' %>
      </div>
      <div class="form-group col-md-1">
        <%= f.label :graduated, "在学/既卒" %>
        <%= f.select :graduated_eq, Profile.graduateds.to_a.map { |w| [w[0].humanize, w[1]] }, {:include_blank => true}, class: 'form-control form-control-sm' %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :profile_course_course_country_id_eq, "参加国" %>
        <%= f.collection_select :profile_course_course_country_id_eq, Country.all, :id, :name, {include_blank: true}, {class: 'form-control form-control-sm'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :profile_course_course_batch_id_eq, "参加期" %>
        <%= f.collection_select :profile_course_course_batch_id_eq, Batch.all, :id, :name, {include_blank: true}, {class: 'form-control form-control-sm'} %>
      </div>

    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
        <%= f.label :school_cont, "学校名" %>
        <%= f.search_field :school_cont, class: 'form-control form-control-sm' %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :major_faculty_name_eq, "専攻(東洋生用)" %>
        <%= f.collection_select :major_faculty_name_eq, Major.select(:faculty_name).distinct, :faculty_name, :faculty_name, {include_blank: true}, {class: 'form-control form-control-sm'} %>
      </div>

      <div class="form-group col-md-3">
        <%= f.label :job_id_eq, "職業" %>
        <%= f.collection_select :job_id_eq, Job.all, :id, :name, {include_blank: true}, {class: 'form-control form-control-sm'} %>
      </div>
      <div class="col-md-3 align-self-center">
        <button type="submit" class="btn btn-primary btn-block">検索する</button>
      </div>
    </div>

    <div class="form-row">

    </div>
    <% end %>
  </div>
</div>
</div>

app/views/profiles/edit.html.erb
<div class="top_main-content mt-4">
  <!--<h3 class="text-center">プロフィール変更</h3>-->
  <%= render partial: "form" %>
</div>

app/views/profiles/index.html.erb
<!--<h3 class="text-center">プロフィール一覧</h3>-->
<div class="mt-4">
  <div class="container">
      <%= render 'search' %>
    <div class="row mb-2">
      <%= render @profiles %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="top_main-content mt-4">
  <!--<h3 class="text-center">プロフィール登録</h3>-->
  <%= render partial: "form" %>
</div>

app/views/profiles/show.html.erb
<article class="resume-wrapper text-center position-relative">
  <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
    <div class="resume-header pt-4 pt-md-0">
      <div class="media flex-column flex-md-row">
        <%= image_tag(@profile.avatar_image.url(:medium), class: 'mr-3 img-fluid picture mx-auto') %>
        <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
          <div class="primary-info">
            <h1 class="name mt-0 mb-1 text-white text-uppercase text-uppercase"><%= @profile.full_name %></h1>
            <h2 class="nickname mt-0 mb-1 text-white text-uppercase text-uppercase">(<%= @profile.nickname %>)</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="resume-body p-5">
      <section class="resume-section summary-section mb-5">
        <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">自己紹介</h2>
        <div class="resume-section-content">
          <p class="mb-0">
            <%= markdown(@profile.description) %>
          </p>
        </div>
      </section>
      <div class="row mb-2">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-9 text-uppercase font-weight-bold">
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a href="#tab1" class="nav-link active" data-toggle="tab">経験</a>
            </li>
            <% if @response.present? %>
              <li class="nav-item">
                <a href="#tab2" class="nav-link" data-toggle="tab">インタビュー</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-3">
          <section class="resume-section language-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">プロフィール情報</h2>
            <div class="resume-section-content">
              <ul class="list-unstyled resume-lang-list">
                <% @profile.profile_course.each do |profile_course| %>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">コース:</span>
                  <%= profile_course.course.full_name %>
                </li>
                <% end %>
                <% if @profile.major.full_name.present? %>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">学部:</span> <%= @profile.major.full_name %></li>
                <% end %>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">在学/既卒:</span> <%= @profile.graduated %></li>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">職業:</span> <%= @profile.job.name %></li>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">誕生日:</span> <%= @profile.birthday %></li>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">性別:</span> <%= @profile.sex %></li>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">最終ログイン:</span> <%= @profile.user.current_sign_in_at.strftime('%m月%d日') %></li>
                <li class="mb-2"><span class="resume-lang-name font-weight-bold">ログイン回数:</span> <%= @profile.user.sign_in_count %></li>
              </ul>
              <% unless @profile.id == current_user.id %>
              <%= link_to '質問する', new_profile_question_url(@profile), class:'btn btn-lg btn-success btn-block gtm-profile-question-request' %>
              <% end %>
            </div>
          </section>
          <section class="resume-section skills-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">リンク</h2>
            <div class="resume-section-content">
              <div class="resume-skill-item">
                <ul class="list-inline">
                  <% if @profile.facebook.present? %>
                  <li class="mb-3">
                    <%= link_to 'Facebook', @profile.facebook, target: '_blank', class: 'gtm-profile-facebook'%>
                  </li>
                  <% end %>
                  <% if @profile.instagram.present? %>
                  <li class="mb-3">
                    <%= link_to 'Instagram', @profile.instagram, target: '_blank', class: 'gtm-profile-instagram'%>
                  </li>
                  <% end %>
                  <% if @profile.twitter.present? %>
                  <li class="mb-3">
                    <%= link_to 'Twitter', @profile.twitter, target: '_blank', class: 'gtm-profile-twitter'%>
                  </li>
                  <% end %>
                  <% if @profile.url_title.present? %>
                  <li class="mb-3">
                    <%= link_to @profile.url_title, @profile.url, target: '_blank', class: 'gtm-profile-other-url'%>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </section>
          <section class="resume-section skills-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">質問- <%= @profile.questioner_question_ids.count %>件</h2>
            <div class="resume-section-content">
              <div class="resume-skill-item">
                <ul class="list-inline">
                  <% @questioner_questions.each do |question| %>
                  <li class="mb-3">
                    <%= link_to question.title, profile_question_url(question.questioned, question.id) %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </section>
          <section class="resume-section skills-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">質問された- <%= @profile.questioned_question_ids.count %>件</h2>
            <div class="resume-section-content">
              <div class="resume-skill-item">
                <ul class="list-inline">
                  <% @questioned_questions.each do |question| %>
                  <li class="mb-3">
                    <%= link_to question.title, profile_question_url(question.questioned, question.id) %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </section>
          <section class="resume-section skills-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">紹介した人- <%= @profile.introducer_introduction_ids.count %>件</h2>
            <div class="resume-section-content">
              <div class="resume-skill-item">
                <ul class="list-inline">
                  <% @introducer_introductions.each do |introduction| %>
                  <li class="mb-3">
                    <%= link_to introduction.introduced.full_name, profile_introduction_url(introduction.introduced, introduction.id) %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </section>
          <% if @profile.user_id == current_user.id %>
          <section class="resume-section skills-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">設定</h2>
            <div class="resume-section-content">
              <div class="resume-skill-item">
                <ul class="list-inline">
                  <li class="mb-3">
                    <%= link_to '招待メール', new_user_invitation_path %>
                  </li>
                  <li class="mb-3">
                    <%= link_to 'プロフィール設定', edit_profile_path(current_user.id)%>
                  </li>
                  <li class="mb-3">
                    <%= link_to 'アカウント設定', edit_user_registration_path %>
                  </li>
                </ul>
              </div>
            </div>
          </section>
          <% end %>
        </div>
        <div class="col-lg-9">
          <div class="tab-content">
            <div id="tab1" class="tab-pane active">
              <!--経験-->
              <section class="resume-section experience-section mb-5">
                <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">
                  経験 - <%= @profile.experience_ids.count %>件
                  <% if @profile.user_id == current_user.id %>
                  <small class="ml-2"><%= link_to '追加', new_profile_experience_url(@profile), class: 'gtm-profile-experience-add' %></small>
                  <% end %>
                </h2>
                <div class="resume-section-content">
                  <% if current_user.profile.experience_ids.count < 5 && @profile.user_id != current_user.id %>
                  <div class="alert alert-warning">
                    <h3 class="text-center mb-3">閲覧制限</h3>
                    <p class="text-center">閲覧には自分の経験の最低5つの登録が必要です。</p>
                    <p class="text-center"><%= link_to '経験追加', new_profile_experience_url(current_user.profile) %>よりご登録お願いします。</p>
                  </div>
                  <% else %>
                  <div class="resume-timeline position-relative">
                    <%= render @experiences %>
                  </div>
                  <small class="ml-2"><%= will_paginate @experiences,:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, :previous_label => ' &lt ', :next_label => ' &gt' %></small>
                  <% end %>
                </div>
              </section>
            </div>
            <div id="tab2" class="tab-pane">
              <!--インタビュー-->
              <section class="resume-section experience-section mb-5">
                <% if @response.present? %>
                  <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3"><%= @response.interview.title %></h2>
                  <%= render :partial => "interviews/interview", :collections => {:response => @response} %>
                <% end %>
              </section>

            </div>
          </div>
          <section class="resume-section experience-section mb-5">
            <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">
              紹介文 - <%= @profile.introduced_introduction_ids.count %>件
              <% if Introduction.find_by(introduced_id: @profile.id, introducer_id: current_user.id).blank? && (@profile.id != current_user.id) %>
              <small class="ml-2"><%= link_to '追加', new_profile_introduction_url(@profile), class: 'gtm-profile-introduction-add' %></small>
              <% end %>
            </h2>
            <div class="resume-section-content">
              <div class="row">
                <%= render @introduced_introductions %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</article>