config/routes.rb
Rails.application.routes.draw do
  get 'mypage/show'
  devise_for :users
  root 'pages#index'
  get 'pages/show'
  get 'terms', to: 'pages#terms'
  get 'policy', to: 'pages#policy'
  get 'questions', to: 'questions#index'
  resources 'profiles' do
    resources 'experiences'
    resources 'introductions'
    resources 'interviews'
    resources 'questions' do
      resources 'answers'
    end
  end
  get 'admin', to: 'admin#index'
  namespace 'admin' do
    resources 'profiles'
    resources 'experiences'
    resources 'questions'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :profile
  belongs_to :question
end

app/models/batch.rb
class Batch < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :batch
  belongs_to :country

  def full_name
    batch.name + name
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :profile

  validates :title, presence: true, length: { maximum: 255 }
  validates :place, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/interview.rb
class Interview < ApplicationRecord
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :introducer, class_name: 'Profile', foreign_key: 'introducer_id'
  belongs_to :introduced, class_name: 'Profile', foreign_key: 'introduced_id'
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/major.rb
class Major < ApplicationRecord
  def full_name
    faculty_name + department_name
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :major
  belongs_to :job
  has_many :profile_course, dependent: :destroy
  has_many :experience, dependent: :destroy
  has_many :introducer_introduction, class_name: 'Introduction', foreign_key: 'introducer_id'
  has_many :introduced_introduction, class_name: 'Introduction', foreign_key: 'introduced_id'
  has_many :questioner_question, class_name: 'Question', foreign_key: 'questioner_id'
  has_many :questioned_question, class_name: 'Question', foreign_key: 'questioned_id'
  has_many :response, dependent: :destroy
  has_many :interview, class_name: 'Interview', foreign_key: 'interview_id'
  accepts_nested_attributes_for :profile_course, allow_destroy: true
  validates :user_id, uniqueness: true
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :nickname, presence: true, length: { maximum: 255 }
  validates :birthday, presence: true
  validates :major_id, presence: true
  validates :avatar_image, presence: true
  validates :facebook, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :instagram, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :twitter, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :url_title, length: { maximum: 7 }
  validates :url, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true
  validates :description, length: { maximum: 255 }
  enum sex: { 女性: 0, 男性: 1, その他: 2 }
  enum usertype: { 学生: 0, スタッフ: 1 }
  enum graduated: { 在学: 0, 既卒: 1 }
  has_attached_file :avatar_image, PAPERCLIP_STORAGE_OPTS
  validates_attachment_content_type :avatar_image, content_type: %r{\Aimage\/.*\Z}

  def full_name
    last_name + first_name
  end
end

app/models/profile_course.rb
class ProfileCourse < ApplicationRecord
  belongs_to :profile
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questioner, class_name: 'Profile', foreign_key: 'questioner_id'
  belongs_to :questioned, class_name: 'Profile', foreign_key: 'questioned_id'
  has_many :answer, dependent: :destroy
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :interview
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable,
         invite_for: 24.hours
  has_one :profile, dependent: :destroy
  has_one :role, dependent: :destroy

  attr_accessor :mode

  def admin?
    role.present?
  end

  def save_role(new_role)
    if role
      role.update(admin_role: new_role)
    else
      role.create_role(admin_role: new_role)
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      space_after_headers: true,
      with_toc_data: true
    }

    extensions = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/index.html.erb
<div class="mx-auto" style="width: 95%">
  <p>
    全ユーザー数: <%= Profile.all.count %>人 /
    男性数: <%= Profile.where(sex: '男性').count %>人 /
    女性数: <%= Profile.where(sex: '女性').count %>人 /
    在学数: <%= Profile.where(graduated: '在学').count %>人 /
    卒業数: <%= Profile.where(graduated: '既卒').count %>人
  </p>

  <p>
    学部割合:
    <% Profile.joins(:major).group(:faculty_name).count.each do |key, value| %>
    <%= key %>: <%= value %>人 /
    <% end %>
  </p>
  <p>
    SNS件数:
    Facebook: <%=Profile.where.not(facebook: "").count %> /
    Instagram: <%=Profile.where.not(twitter: "").count %> /
    Instagram: <%=Profile.where.not(instagram: "").count %> /
  </p>

  <p>全経験数: <%= Experience.all.count %>件</p>
</div>

app/views/layouts/_flush.html.erb
<% flash.each do |message_type, message| %>
    <%if message_type.to_s != "timedout" %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-8">
        <span class="text-muted"><%= link_to '利用規約', terms_path  %></span>
        <span class="text-muted"><%= link_to 'プライバシーポリシー', policy_path  %></span>
      </div>
      <div class="col-md-4">
        <span class="text-muted">Copyright © GIFTECH All Rights Reserved.</span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container">


    <nav class="navbar navbar-expand-md navbar-light">
      <a class="navbar-brand" href="/">Voyagers.app</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <!--<strong><%= link_to current_user.id, pages_show_path %></strong>-->
          <!--<li class="nav-item">
            <%= link_to '基本情報変更', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'プロフィール変更', edit_profile_path(current_user.id), class: 'nav-link' %>
          </li>-->
          <li class="nav-item">
            <%= link_to 'プロフィール一覧', profiles_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '質問一覧', questions_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <% else %>
          <!--<li class="nav-item">
            <%= link_to 'サインアップ', new_user_registration_path, class: 'nav-link' %>
          </li>-->
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
          </li>
          <% end %>

          <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>
</div>


</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voyagers.app</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Voyagers.appはDiversityVoyage卒業生の非公式プラットフォームです。">
  <meta property="og:title"       content="Voyagers.app">
  <meta property="og:description" content="Voyagers.appはDiversityVoyage卒業生の非公式プラットフォームです。" />
  <meta property="og:type"        content="website" />
  <meta property="og:url"         content="https://www.voyagers.app" />
  <meta property="og:image"       content="https://www.voyagers.app/assets/earth_ogp-26d7547239ff0a1dda12586aa4aedd524a0ceb3c3c24d7dacc284d6dc6d73352.png" />
  <meta name="twitter:card"       content="summary" />
  <%= analytics_init if Rails.env.production? %>
  <%= favicon_link_tag('favicon.ico') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-light">
        <a class="navbar-brand" href="/admin">Voyagers.app</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'プロフィール一覧', admin_profiles_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '経験一覧', admin_experiences_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問一覧', admin_questions_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voyagers.app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Voyagers.appはDiversityVoyage卒業生の非公式プラットフォームです。">
    <meta property="og:title"       content="Voyagers.app">
    <meta property="og:description" content="Voyagers.appはDiversityVoyage卒業生の非公式プラットフォームです。" />
    <meta property="og:type"        content="website" />
    <meta property="og:url"         content="https://www.voyagers.app" />
    <meta property="og:image"       content="https://www.voyagers.app/assets/earth_ogp-26d7547239ff0a1dda12586aa4aedd524a0ceb3c3c24d7dacc284d6dc6d73352.png" />
    <meta name="twitter:card"       content="summary" />
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PQC5VZM');</script>
    <!-- End Google Tag Manager -->
    <%= analytics_init if Rails.env.production? %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PQC5VZM"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <%= render 'layouts/header' %>
    <%= render 'layouts/flush' %>
      <%= yield %>
  </body>
</html>